/**
 * AGENTS.md export — generate a cross-agent compatible AGENTS.md file
 * from installed skills. Works with Cursor, Windsurf, Codex, Cline,
 * Gemini CLI, and any agent that reads AGENTS.md.
 *
 * Each skill is wrapped in an XML-like <skill> block with its name
 * as an attribute, frontmatter stripped, markdown content preserved.
 */

import fs from "fs";
import path from "path";

// ── Types ──

export interface AgentsMdEntry {
	name: string;
	content: string; // raw SKILL.md content
}

export interface ExportResult {
	skillCount: number;
	outputPath: string;
	totalChars: number;
}

// ── Frontmatter stripping ──

function stripFrontmatter(content: string): string {
	const trimmed = content.trimStart();
	if (!trimmed.startsWith("---")) return content;

	const endIdx = trimmed.indexOf("---", 3);
	if (endIdx === -1) return content;

	return trimmed.slice(endIdx + 3).trim();
}

// ── Rendering ──

export function renderAgentsMdBlock(name: string, rawContent: string): string {
	const body = stripFrontmatter(rawContent);
	return `<skill name="${name}">\n${body}\n</skill>`;
}

export function renderAgentsMdFile(
	entries: AgentsMdEntry[],
	projectName: string = "project",
): string {
	const lines: string[] = [];

	lines.push("# AGENTS.md");
	lines.push("");
	lines.push(
		`> Generated by javi-ai for **${projectName}** — ${entries.length} skills`,
	);
	lines.push(">");
	lines.push(
		"> This file is compatible with Claude Code, Cursor, Codex, Windsurf, Cline, and Gemini CLI.",
	);
	lines.push("");

	for (const entry of entries) {
		lines.push(renderAgentsMdBlock(entry.name, entry.content));
		lines.push("");
	}

	return lines.join("\n");
}

// ── Export from disk ──

export function exportToAgentsMd(
	skillsDir: string,
	outputPath: string,
	filterNames?: string[],
	projectName?: string,
): ExportResult {
	if (!fs.existsSync(skillsDir)) {
		const empty = renderAgentsMdFile([], projectName);
		const dir = path.dirname(outputPath);
		if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(outputPath, empty);
		return { skillCount: 0, outputPath, totalChars: empty.length };
	}

	const entries: AgentsMdEntry[] = [];
	const dirEntries = fs.readdirSync(skillsDir, { withFileTypes: true });

	for (const entry of dirEntries) {
		if (!entry.isDirectory()) continue;
		if (entry.name.startsWith("_")) continue;
		if (filterNames && !filterNames.includes(entry.name)) continue;

		const skillMd = path.join(skillsDir, entry.name, "SKILL.md");
		if (!fs.existsSync(skillMd)) continue;

		const content = fs.readFileSync(skillMd, "utf-8");
		entries.push({ name: entry.name, content });
	}

	// Sort alphabetically
	entries.sort((a, b) => a.name.localeCompare(b.name));

	const output = renderAgentsMdFile(entries, projectName);
	const dir = path.dirname(outputPath);
	if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
	fs.writeFileSync(outputPath, output);

	return {
		skillCount: entries.length,
		outputPath,
		totalChars: output.length,
	};
}
