/**
 * Integration tests for uninstall — marker stripping, backup restore, hooks removal.
 * Uses real filesystem, mocking only paths.
 */

import fs from "fs-extra";
import path from "path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const {
	FIXED_ROOT,
	FIXED_HOME,
	FIXED_MANIFEST,
	FIXED_BACKUP,
	FIXED_CLAUDE_CONFIG,
	FIXED_CLAUDE_SKILLS,
} = vi.hoisted(() => {
	const p = require("path");
	const o = require("os");
	const root = p.join(o.tmpdir(), `javi-ai-uninstall-test-${Date.now()}`);
	const home = p.join(root, "home");
	return {
		FIXED_ROOT: root as string,
		FIXED_HOME: home as string,
		FIXED_MANIFEST: p.join(home, ".javi-ai", "manifest.json") as string,
		FIXED_BACKUP: p.join(home, ".javi-ai", "backups") as string,
		FIXED_CLAUDE_CONFIG: p.join(home, ".claude") as string,
		FIXED_CLAUDE_SKILLS: p.join(home, ".claude", "skills") as string,
	};
});

vi.mock("../constants.js", () => ({
	HOME: FIXED_HOME,
	CLI_OPTIONS: [
		{
			id: "claude",
			label: "Claude Code",
			configPath: FIXED_CLAUDE_CONFIG,
			skillsPath: FIXED_CLAUDE_SKILLS,
			pluginsPath: FIXED_CLAUDE_CONFIG + "/plugins",
			available: true,
		},
	],
	MANIFEST_PATH: FIXED_MANIFEST,
	BACKUP_DIR: FIXED_BACKUP,
	MARKER_START: "<!-- BEGIN JAVI-AI -->",
	MARKER_END: "<!-- END JAVI-AI -->",
}));

const MARKER_START = "<!-- BEGIN JAVI-AI -->";
const MARKER_END = "<!-- END JAVI-AI -->";

vi.mock("../installer/manifest.js", () => ({
	readManifest: async () => {
		const fse = require("fs-extra");
		if (await fse.pathExists(FIXED_MANIFEST))
			return fse.readJson(FIXED_MANIFEST);
		return {
			version: "1.0.0",
			clis: [],
			installedAt: "",
			updatedAt: "",
			skills: {},
		};
	},
}));

import type { UninstallItem } from "../commands/uninstall.js";
import { buildUninstallPlan, runUninstall } from "../commands/uninstall.js";

describe("uninstall — integration", () => {
	beforeEach(async () => {
		await fs.ensureDir(FIXED_HOME);
	});

	afterEach(async () => {
		await fs.remove(FIXED_ROOT);
	});

	async function setupInstallation() {
		// Create manifest
		await fs.ensureDir(path.dirname(FIXED_MANIFEST));
		await fs.writeJson(FIXED_MANIFEST, {
			version: "1.0.0",
			clis: ["claude"],
			installedAt: new Date().toISOString(),
			updatedAt: new Date().toISOString(),
			skills: {},
		});
		// Create skills dir
		await fs.ensureDir(FIXED_CLAUDE_SKILLS);
		await fs.ensureDir(path.join(FIXED_CLAUDE_SKILLS, "react-19"));
		await fs.writeFile(
			path.join(FIXED_CLAUDE_SKILLS, "react-19", "SKILL.md"),
			"# React 19",
		);
		// Create hooks
		await fs.ensureDir(path.join(FIXED_CLAUDE_CONFIG, "hooks"));
		await fs.writeFile(
			path.join(FIXED_CLAUDE_CONFIG, "hooks", "comment-check.sh"),
			"#!/bin/bash",
		);
		// Create CLAUDE.md with markers
		const claudeMd = [
			"# My Rules",
			"",
			"Custom content here.",
			"",
			MARKER_START,
			"# AI Config",
			"Generated by javi-ai.",
			MARKER_END,
		].join("\n");
		await fs.writeFile(path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"), claudeMd);
	}

	it("buildUninstallPlan includes skills, hooks, config sections, manifest", async () => {
		await setupInstallation();
		const { clis, items } = await buildUninstallPlan();

		expect(clis).toContain("claude");
		expect(items.some((i) => i.type === "skills-dir")).toBe(true);
		expect(items.some((i) => i.type === "hooks-dir")).toBe(true);
		expect(items.some((i) => i.type === "config-section")).toBe(true);
		expect(items.some((i) => i.type === "manifest")).toBe(true);
	});

	it("runUninstall removes skills directory", async () => {
		await setupInstallation();
		const items: UninstallItem[] = [
			{
				label: "skills",
				path: FIXED_CLAUDE_SKILLS,
				type: "skills-dir",
				cli: "claude",
			},
		];

		const result = await runUninstall(items);
		expect(result.removed.length).toBeGreaterThan(0);
		expect(await fs.pathExists(FIXED_CLAUDE_SKILLS)).toBe(false);
	});

	it("runUninstall removes manifest", async () => {
		await setupInstallation();
		const items: UninstallItem[] = [
			{
				label: "manifest",
				path: FIXED_MANIFEST,
				type: "manifest",
			},
		];

		const result = await runUninstall(items);
		expect(result.removed.length).toBe(1);
		expect(await fs.pathExists(FIXED_MANIFEST)).toBe(false);
	});

	it("runUninstall strips marker section from CLAUDE.md, preserves user content", async () => {
		await setupInstallation();
		const items: UninstallItem[] = [
			{
				label: "CLAUDE.md",
				path: path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"),
				type: "config-section",
				cli: "claude",
			},
		];

		const result = await runUninstall(items);
		expect(result.removed.length).toBe(1);

		const content = await fs.readFile(
			path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"),
			"utf-8",
		);
		// User content preserved
		expect(content).toContain("# My Rules");
		expect(content).toContain("Custom content here.");
		// Markers and javi-ai content removed
		expect(content).not.toContain(MARKER_START);
		expect(content).not.toContain(MARKER_END);
		expect(content).not.toContain("Generated by javi-ai");
	});

	it("runUninstall deletes file if only javi-ai content", async () => {
		await setupInstallation();
		// Overwrite CLAUDE.md with ONLY marker content
		const onlyMarkers = `${MARKER_START}\nAI only\n${MARKER_END}`;
		await fs.writeFile(
			path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"),
			onlyMarkers,
		);

		const items: UninstallItem[] = [
			{
				label: "CLAUDE.md",
				path: path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"),
				type: "config-section",
				cli: "claude",
			},
		];

		await runUninstall(items);
		// File should be completely removed
		expect(
			await fs.pathExists(path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md")),
		).toBe(false);
	});

	it("runUninstall restores from backup when available", async () => {
		await setupInstallation();
		// Create a backup
		const backupTs = "2026-03-22T00-00-00";
		const backupClaudeDir = path.join(FIXED_BACKUP, backupTs, "claude");
		await fs.ensureDir(backupClaudeDir);
		await fs.writeFile(
			path.join(backupClaudeDir, "CLAUDE.md"),
			"# Original backup content\n",
		);

		const items: UninstallItem[] = [
			{
				label: "CLAUDE.md",
				path: path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"),
				type: "config-section",
				cli: "claude",
			},
		];

		const result = await runUninstall(items);
		expect(result.restored.length).toBe(1);

		const content = await fs.readFile(
			path.join(FIXED_CLAUDE_CONFIG, "CLAUDE.md"),
			"utf-8",
		);
		expect(content).toBe("# Original backup content\n");
	});

	it("runUninstall removes only javi-ai hooks (preserves user hooks)", async () => {
		await setupInstallation();
		// Add a user-created hook
		await fs.writeFile(
			path.join(FIXED_CLAUDE_CONFIG, "hooks", "my-custom-hook.sh"),
			"#!/bin/bash\necho mine",
		);

		const items: UninstallItem[] = [
			{
				label: "hooks",
				path: path.join(FIXED_CLAUDE_CONFIG, "hooks"),
				type: "hooks-dir",
				cli: "claude",
			},
		];

		const result = await runUninstall(items);

		// User hook should still exist
		expect(
			await fs.pathExists(
				path.join(FIXED_CLAUDE_CONFIG, "hooks", "my-custom-hook.sh"),
			),
		).toBe(true);

		// javi-ai hook should be removed (if it matched own/hooks/claude files)
		// The removed list should have entries
		expect(result.removed.length).toBeGreaterThanOrEqual(0);
	});
});
