export {
	addInstinct,
	boostConfidence,
	createCollection,
	createInstinct,
	findByTag,
	formatInstincts,
	fromJSON,
	getActiveInstincts,
	type Instinct,
	type InstinctCollection,
	penalizeConfidence,
	recordUsage,
	removeInstinct,
	toJSON,
	validateRule,
} from "./instinct.js";
